// Error Handling

try{

    // business

} catch(err){
    // error
}

// xxxyyy;

try {
    console.log("Starts of try..");

    xxxxyyyy;
    let x = 90/0;
    console.log("End of try..")
    
} catch (error) {
    // console.log("Something error...")
    console.log(error.message);
}

